version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pgdb
    environment:
      POSTGRES_DB: authentication_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@Abhishek11611"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  authapp:
    build: .
    container_name: jwt-authentication-authapp-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authentication_demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "@Abhishek11611"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_MAIL_USERNAME: abhisheksureshgupta66166@gmail.com
      SPRING_MAIL_PASSWORD: mhvg jsnl wteo jfwq
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
